CREATE TABLE IF NOT EXISTS test_sync (
  id INT AUTO_INCREMENT PRIMARY KEY,
  msg VARCHAR(100)
);
CREATE TABLE IF NOT EXISTS sessions (
  id VARCHAR(255) PRIMARY KEY,
  data TEXT,
  last_access TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
